### ISSUE TITLE
Send an alarm to the dashboard in the case of a fall

### ISSUE THREAD

**Issue by tcarlyle** [iverasp/project_gravity#22]
The app should send an alarm to the dashboard https://github.com/SINTEF-SIT/emht in the case of a fall.

Sending an alarm consist of sending a POST request to http://serverADDRESS/alarm
with the following payload:

type=fall&callee.phoneNumber=phoneNumber&callee.name=name&callee.address=address

where both:
serverADDRESS
phoneNumber
name
address

should be configurable through a config file.

It is important that in case the app is offline or if the server is down, the application should not crash

**Comment by iverasp** [comment]
configurable through resources/src/main/res/values/emht.xml
tested with device online and offline
